version: '2'
services:
  restheart:
    build: docker/restheart
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4
    command: "mongod --replSet rs0"
    volumes:
      - mongodata:/data/db

  mongodb-setup:
    build: mongodb
    depends_on:
      - mongodb
    restart: on-failure

  # Acts as a reverse proxy for pretty much everything
  nginx:
    build: docker/nginx
    depends_on:
      - restheart
      - webapp

  # Builds and serves static content
  webapp:
    build: webapp

volumes:
  mongodata: {}
