version: '2'
services:
  restheart:
    build: docker/restheart
    depends_on:
      - mongodb
    networks:
      - db
      - frontend

  mongodb:
    image: mongo:3.4
    command: "mongod --replSet rs0"
    volumes:
      - mongodata:/data/db
    networks:
      - db

  mongodb-setup:
    build: docker/mongodb-setup
    depends_on:
      - mongodb
    networks:
      - db
    restart: on-failure

  # Acts as a reverse proxy and does auth for RESTheart
  # Also serves static content
  nginx:
    build: docker/nginx
    depends_on:
      - restheart
    networks:
      - frontend

volumes:
  mongodata: {}

networks:
  db: {}
  frontend: {}
