version: '2'
services:
  restheart:
    ports:
      - "127.0.15.1:8080:8080"
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password

  nginx:
    environment:
      NGINX_HOSTNAME: rem.dev
      NO_LETSENCRYPT: "true"
    ports:
      - "127.0.15.1:80:80"
      - "127.0.15.1:443:443"
    volumes:
      - "./dev-ssl:/etc/letsencrypt/live/rem.dev"
      - "./webapp/tmp:/build"
