apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: rem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: static
        image: keitwb/rem-webapp:dev
        ports:
        - containerPort: 80
