---
- template: src=docker-compose.prod.yml.j2 dest=/etc/docker-compose.rem.yml mode=0600
- template: src=dc.j2 dest=/usr/local/bin/dc-rem mode=0755

- name: Build all docker images
  command: dc-rem build

- name: Start containers
  command: dc-rem up -d

- include: ssl.yml
  vars:
    domain: "{{ admin_hostname }}"
    refresh_command: "/usr/local/bin/dc-rem exec nginx_https kill -HUP 1"
    tags:
      - ssl

- command: docker images --filter dangling=true -q
  register: dangling_images

- name: Remove dangling images
  shell: "docker rmi {{ dangling_images.stdout_lines | join(' ') }}"
  when: dangling_images.stdout
  ignore_errors: true
