---
- name: Install base packages
  apt: name={{item}} state=present
  with_items:
    - git
    - aptitude
- name: Upgrade all packages
  apt: upgrade=safe

- name: Create docker-run dir
  file: state=directory name=/docker-run mode=0755

- include: repo.yml
- include: containers.yml
- include: backup.yml

