---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: es
  labels:
    app: es
spec:
  # This needs to be more advanced to support more than one instance
  replicas: 1
  selector:
    matchLabels:
      app: es
  serviceName: es
  template:
    metadata:
      labels:
        app: es
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: Always
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: init-mount
        image: busybox
        imagePullPolicy: Always
        command: ["chown", "1000.1000", "-R", "/usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: ephemeral
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: es-setup
        image: python:3.7-alpine
        command: ["tail"]
        args: ["-f", "/dev/null"]
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: node.name
          value: es01
        - name: cluster.initial_master_nodes
          value: es01
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: ephemeral
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: ephemeral
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  selector:
    app: es
  type: NodePort
  ports:
  - name: tcp
    port: 9200
    targetPort: 9200
