---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: rem
spec:
  selector:
    app: mongo
  type: NodePort
  ports:
  - name: tcp
    port: 27017
    targetPort: 27017
    nodePort: 31000
