---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
      - "{{ .Values.ingressHost }}"
      secretName: ingress-tls
  rules:
  - host: "{{ .Values.ingressHost }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-websockets
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.allow-http: "false"
    # Set to one hour for websocket connections
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  tls:
    - hosts:
      - "{{ .Values.ingressHost }}"
      secretName: ingress-tls
  rules:
  - host: "{{ .Values.ingressHost }}"
    http:
      paths:
      - path: /stream
        backend:
          serviceName: data-streamer
          servicePort: 8080
