---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  # This needs to be more advanced to support more than one instance
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: mongo
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: mongo
        image: quay.io/rem/mongo:{{default .Values.defaultTag  .Values.mongoImageTag }}
        imagePullPolicy: Always
        command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "rs0"
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: "/data/db"
            name: data
      - name: setup
        image: quay.io/rem/mongo:{{default .Values.defaultTag  .Values.mongoImageTag }}
        imagePullPolicy: Always
        env:
          - name: STAY_UP
            value: "yes"
        command:
        - "/opt/setup/run.sh"
      {{if .Values.mongoEphemeralDisk }}
      volumes:
        - name: data
          emptyDir:
            medium: Memory
      {{end}}
  {{if not .Values.mongoEphemeralDisk}}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
  {{end}}
