{{ if false }} {{/* Disable the mongo statefulset */}}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: mongo
    release: "{{ .Release.Name }}"
  clusterIP: None
  ports:
  - name: tcp
    port: 27017
    targetPort: 27017
{{end}}
