---
apiVersion: v1
kind: Service
metadata:
  name: restheart
  labels:
    app: restheart
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: restheart
    release: "{{ .Release.Name }}"
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
