---
apiVersion: v1
kind: Service
metadata:
  name: tika
  labels:
    app: tika
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: tika
    release: "{{ .Release.Name }}"
  clusterIP: None
  ports:
  - name: tcp
    port: 9998
    targetPort: 9998
