apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: update-streamer
spec:
  replicas: {{ .Values.updateStreamer.replicas }}
  selector:
    matchLabels:
      app: update-streamer
  template:
    metadata:
      labels:
        app: update-streamer
    spec:
      containers:
      - name: update-streamer
        image: quay.io/rem/update-streamer:{{ .Values.updateStreamer.image.tag }}
        imagePullPolicy: {{ .Values.updateStreamer.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_HOSTNAME
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
