apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.webappReplicas }}
  selector:
    matchLabels:
      app: webapp
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: webapp
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: static
        image: quay.io/rem/webapp:{{default .Values.defaultTag  .Values.webappImageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
