apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: static
        image: quay.io/rem/webapp:{{ .Values.webapp.image.tag }}
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /build/dist
          name: dev
      volumes:
      - name: dev
        hostPath:
          path: /code/webapp/dist
          type: Directory
