apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      app: webapp
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: webapp
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: static
        image: quay.io/rem/webapp:{{ .Values.webapp.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      {{ if .Values.devMode }}
        volumeMounts:
        - mountPath: /build/dist
          name: dev
      volumes:
      - name: dev
        hostPath:
          path: "{{ .Values.webapp.distDir }}"
          type: Directory
      {{ end }}
