---
 - set_fact: docker_version=1.11.1
 - name: Download Docker {{docker_version}} deb package
   get_url: url=https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_{{docker_version}}-0~jessie_amd64.deb
            dest=/opt/docker-{{docker_version}}.deb

 - name: Install docker
   apt: deb=/opt/docker-{{docker_version}}.deb dpkg_options=skip-same-version update_cache=yes state=present

 - name: Install easy_install
   apt: name=python-setuptools state=present

 - name: Install python pip
   easy_install: name=pip state=present

 - name: Install docker-compose
   pip: name=docker-compose version=1.7.0 state=present
